### Invalid GET request
GET http://localhost:5000/invalid-route HTTP/1.1

### Invalid POST request
POST http://localhost:5000/invalid-route HTTP/1.1

### Invalid PATCH request
PATCH http://localhost:5000/invalid-route HTTP/1.1

### Invalid PUT request
PUT http://localhost:5000/invalid-route HTTP/1.1

### Invalid DELETE request
DELETE http://localhost:5000/invalid-route HTTP/1.1