### Admin Login Request
POST http://localhost:5000/admin/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin@123"
}

### Get Online users
GET http://localhost:5000/admin/registration-list/users

### Update Authorizations
PATCH http://localhost:5000/admin/registration-list/d799d6adfe605445127eae81b9e4be/authorization
Content-Type: application/json

{
    "authorized": 1
}

### Add User
POST http://localhost:5000/admin/registration-list/user/d799d6adfe605445127eae81b9e4be/add

### Map Client
PUT http://localhost:5000/admin/registration-list/map
Content-Type: application/json

{
    "userId": "d799d6adfe605445127eae81b9e4be",
    "accoid": 1
}

### Get Tenderbalances Details
GET http://localhost:5000/admin/publish-list/tenderbalances

### Inser into Daily Publish
POST http://localhost:5000/admin/publish-list/dailypublish
Content-Type: application/json

{
    "tender_no": 2624,
    "tender_date": "2022-09-13",
    "mill_short_name": "AINDRESHWAR",
    "item_name": "SUGAR 50 KG",
    "payment_to_name": "AINDRESHWAR",
    "tender_do_name": "SELF",
    "season": "20-21",
    "grade": "ORD S/30 (S2)",
    "quantal": 18000,
    "lifting_date": "2022-09-16",
    "purchase_rate": 0,
    "mill_rate": 3330,
    "mc": 2462,
    "pt": 2462,
    "item_code": 1,
    "tender_id": 2687,
    "td": 2,
    "mill_code": 80958,
    "tender_do": 2,
    "payment_to": 80958,
    "balance": 18000,
    "buyer": 2,
    "unit": "Q",
    "sale_rate": 100,
    "publish_quantal": 150,
    "multiple_of": 160,
    "auto_confirm": "Y",
    "type": "F",
    "ic": 1
}

### Get Daily Publish
GET http://localhost:5000/admin/published-list/dailybalance

### Update Single trade status
PATCH http://localhost:5000/admin/published-list/trade/status
Content-Type: application/json

{
    "tender_id": 2593,
    "status": "N"
}

### Update All trade status
PATCH http://localhost:5000/admin/published-list/trade/status/all
Content-Type: application/json

{
    "status": "N"
}

###  update sale rate for trade
PATCH http://localhost:5000/admin/published-list/trade/sale_rate
Content-Type: application/json

{
    "tender_id": 2593,
    "sale_rate": -5
}

###  update sale rate for all trade
PATCH http://localhost:5000/admin/published-list/trade/sale_rate/all
Content-Type: application/json

{
    "sale_rate": 5
}

###  modify trade
PATCH http://localhost:5000/admin/published-list/trade/update
Content-Type: application/json

{
    "tender_id": 2593,
    "published_qty": 1000,
    "sale_rate": 5
}