export { DEFAULT_PATH, AUTH_PATH, AUTH_LOGIN_PATH, AUTH_REGISTER_PATH } from "./AuthPath";
export { ADMIN_PATH, ADMIN_MAP_PATH, ADMIN_REGISTRATION_LIST_PATH } from "./AdminPath";
export { USER_HOME_PATH, USER_NO_AUTHORIZATION_PATH, USER_REGISTER_PATH} from "./UserPath";
export const ALL_PATHS = [
    DEFAULT_PATH,
    AUTH_PATH,
    AUTH_LOGIN_PATH,
    AUTH_REGISTER_PATH,
    ADMIN_PATH,
    ADMIN_MAP_PATH,
    ADMIN_REGISTRATION_LIST_PATH,
    USER_HOME_PATH,
    USER_NO_AUTHORIZATION_PATH,
    USER_REGISTER_PATH
];