export const USER_AUTH_START = "USER_AUTH_START"
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS"
export const USER_AUTH_FAIL = "USER_AUTH_FAIL"

export const ADMIN_AUTH_START = "ADMIN_AUTH_START"
export const ADMIN_AUTH_SUCCESS = "ADMIN_AUTH_SUCCESS"
export const ADMIN_AUTH_FAIL = "ADMIN_AUTH_FAIL"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_ADMIN = "LOGOUT_ADMIN"
